name: Meson CI

on:
  push:
    paths:
      - "**.py"
      - "**.build"
      - "**.options"
  pull_request:
    paths:
      - "**.py"
      - "**.build"
      - "**.options"

jobs:
  build:
    name: Build and Test on ${{ matrix.os }} with Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Tests
        run: |
          if [ -f pytest.ini ]; then pytest; fi

      - name: Upload Test Log
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}_python_${{ matrix.python-version }}_testlog
          path: ./testlog.txt
